Update URLs to point to developer.mbed.org
Data gets lost in the redirect from mbed.org-> developer.mbed.org,
which leaves authentication failing:

DEBUG:root:Authorization Required
...
Exception: Error while talking to the mbed API

This change returns the example script to working state.